# Generated by Django 3.2.7 on 2021-11-14 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0002_auto_20211109_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 10, 17, 13, 771410, tzinfo=utc)),
        ),
    ]
