# Generated by Django 3.2.7 on 2021-10-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'корзина', 'verbose_name_plural': 'корзины'},
        ),
        migrations.RemoveField(
            model_name='basket',
            name='slug',
        ),
    ]
